# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title: 近寐遥喧 
tagline: 毕竟五月只在春天来一遭
description: 近寐遥喧 
url: https://maybe2020.github.io
baseurl: ""
paginate: 10

# About/contact
author:
  name: 岚
  url:
  email: maybe2020@gmail.com

# Custom vars
version: 1.0.0

# Archive
plugins:
  - jekyll-archives
# bundle exec jekyll serve
