auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “近寐遥嚣”
title: May's blog
description: 春天只在五月来一遭.
url: http://maybe2020.github.io
feed: /atom.xml
author_info: <a href="http://maybe2020.github.io/">Maybe2020</a>
